const games = [
  ['3D Cube World', 'auto-3d-cube-world', 'Play 3D Cube World - 3D game!', '3D', '/games/auto-3d-cube-world/index.html', 1, 0, 0],
  ['3D Particle Explorations', 'jackrugile-3d-particle-explorations', 'Play 3D Particle Explorations - Puzzle game!', 'Puzzle', '/games/jackrugile-3d-particle-explorations/index.html', 14, 0, 0],
  ['Aditya Raj - Crossy Road Game Clone', 'unanimousaditya-crossy-road-game', 'Play Aditya Raj - Crossy Road Game Clone - Arcade game!', 'Arcade', '/games/unanimousaditya-crossy-road-game/index.html', 3, 0, 0],
  ['AI Game Hub', 'somyadipghosh-web-games', 'Play AI Game Hub - Puzzle game!', 'Puzzle', '/games/somyadipghosh-web-games/index.html', 13, 0, 0],
  ['Alien Armada', 'kittykatattack-ga', 'Play Alien Armada - Shooting game!', 'Shooting', '/games/kittykatattack-ga/04_alienArmada.html', 5, 0, 0],
  ['Arcade Shooter 1', 'auto-shooter-v0', 'Play Arcade Shooter 1 - Action shooter!', 'Shooting', '/games/auto-shooter-v0/index.html', 2, 0, 0],
  ['Arcade Shooter 2', 'auto-shooter-v1', 'Play Arcade Shooter 2 - Action shooter!', 'Shooting', '/games/auto-shooter-v1/index.html', 2, 0, 0],
  ['Arcade Shooter 3', 'auto-shooter-v2', 'Play Arcade Shooter 3 - Action shooter!', 'Shooting', '/games/auto-shooter-v2/index.html', 2, 0, 0],
  ['Arena5 - HTML5 Canvas JavaScript Game!', 'kevinroast-arena5', 'Play Arena5 - HTML5 Canvas JavaScript Game! - Puzzle game!', 'Puzzle', '/games/kevinroast-arena5/index.html', 6, 0, 0],
  ['Arkanoid en JavaScript', 'midudev-javascript-100-proyectos', 'Play Arkanoid en JavaScript - Puzzle game!', 'Puzzle', '/games/midudev-javascript-100-proyectos/index.html', 4, 0, 0],
  ['Armor Alley: Remastered', 'scottschiller-armoralley', 'Play Armor Alley: Remastered - Puzzle game!', 'Puzzle', '/games/scottschiller-armoralley/index.html', 1, 0, 0],
  ['Asteroids 1', 'auto-asteroids-v0', 'Play Asteroids 1 - Arcade game!', 'Arcade', '/games/auto-asteroids-v0/index.html', 2, 0, 0],
  ['Asteroids 2', 'auto-asteroids-v1', 'Play Asteroids 2 - Arcade game!', 'Arcade', '/games/auto-asteroids-v1/index.html', 2, 0, 0],
  ['Asteroids 3', 'auto-asteroids-v2', 'Play Asteroids 3 - Arcade game!', 'Arcade', '/games/auto-asteroids-v2/index.html', 2, 0, 0],
  ['Backgammon', 'auto-backgammon', 'Play Backgammon - Board game!', 'Board', '/games/auto-backgammon/index.html', 1, 0, 0],
  ['Backgammon GUI', 'MateiCosa-backgammon-ai', 'Play Backgammon GUI - Board game!', 'Board', '/games/MateiCosa-backgammon-ai/index.html', 3, 0, 0],
  ['baiducbit AI Studio - FLUX翻译工作流', 'reneverland-CBIT-AiStudio', 'Play baiducbit AI Studio - FLUX翻译工作流 - Puzzle game!', 'Puzzle', '/games/reneverland-CBIT-AiStudio/index_backup.html', 4, 0, 0],
  ['Ball Blaster', 'auto-ball-blaster', 'Play Ball Blaster - Shooting game!', 'Shooting', '/games/auto-ball-blaster/index.html', 1, 0, 0],
  ['Ball Bounce 1', 'auto-ball-bounce-v0', 'Play Ball Bounce 1 - Arcade game!', 'Arcade', '/games/auto-ball-bounce-v0/index.html', 2, 0, 0],
  ['Ball Bounce 2', 'auto-ball-bounce-v1', 'Play Ball Bounce 2 - Arcade game!', 'Arcade', '/games/auto-ball-bounce-v1/index.html', 2, 0, 0],
  ['Ball Bounce 3', 'auto-ball-bounce-v2', 'Play Ball Bounce 3 - Arcade game!', 'Arcade', '/games/auto-ball-bounce-v2/index.html', 2, 0, 0],
  ['Battle Royale - Social Stream Ninja', 'steveseguin-social_stream', 'Play Battle Royale - Social Stream Ninja - Puzzle game!', 'Puzzle', '/games/steveseguin-social_stream/battle.html', 108, 0, 0],
  ['BBC Floats', 'arnoldpires-100devsbootcamp', 'Play BBC Floats - Puzzle game!', 'Puzzle', '/games/arnoldpires-100devsbootcamp/index.html', 1, 0, 0],
  ['Behind Asteroids', 'gre-behind-asteroids', 'Play Behind Asteroids - Arcade game!', 'Arcade', '/games/gre-behind-asteroids/target.html', 20, 0, 0],
  ['Bellwoods', 'mattdesl-bellwoods', 'Play Bellwoods - Arcade game!', 'Arcade', '/games/mattdesl-bellwoods/index.html', 8, 0, 0],
  ['Black Jack', 'oli8-blackjackjs', 'Play Black Jack - Card game!', 'Card', '/games/oli8-blackjackjs/index.html', 2, 0, 0],
  ['Blackjack 1', 'auto-blackjack-v0', 'Play Blackjack 1 - Card game!', 'Card', '/games/auto-blackjack-v0/index.html', 2, 0, 0],
  ['Blackjack 2', 'auto-blackjack-v1', 'Play Blackjack 2 - Card game!', 'Card', '/games/auto-blackjack-v1/index.html', 2, 0, 0],
  ['Blackjack 3', 'auto-blackjack-v2', 'Play Blackjack 3 - Card game!', 'Card', '/games/auto-blackjack-v2/index.html', 2, 0, 0],
  ['Blackjack Vegas', 'auto-blackjack-vegas', 'Play Blackjack Vegas - Card game!', 'Card', '/games/auto-blackjack-vegas/index.html', 1, 0, 0],
  ['BlastEngine!', 'greypants-blastengine', 'Play BlastEngine! - Puzzle game!', 'Puzzle', '/games/greypants-blastengine/index.html', 2, 0, 0],
  ['Blockchain Technology - Possibilities for the US Postal Service', 'sambacha-compendium', 'Play Blockchain Technology - Possibilities for the US Postal Service - Puzzle game!', 'Puzzle', '/games/sambacha-compendium/Blockchain-Technology-Possibilities-for-the-US-Postal-Service.html', 4, 0, 0],
  ['Blueprint 3D - Example', 'aalavandhaann-blueprint-js', 'Play Blueprint 3D - Example - Puzzle game!', 'Puzzle', '/games/aalavandhaann-blueprint-js/index2.html', 4, 0, 0],
  ['BodyVisualiser', 'OpnTec-bodyapps-viz', 'Play BodyVisualiser - 3D game!', '3D', '/games/OpnTec-bodyapps-viz/index.html', 5, 0, 0],
  ['Bounce Back', 'killedbyapixel-bounceback', 'Play Bounce Back - Arcade game!', 'Arcade', '/games/killedbyapixel-bounceback/index.html', 8, 0, 0],
  ['brain.js示例', 'dashnowords-imfe', 'Play brain.js示例 - Arcade game!', 'Arcade', '/games/dashnowords-imfe/xor-demo-[i,j].html', 3, 0, 0],
  ['Brainchop', 'neuroneural-brainchop', 'Play Brainchop - Card game!', 'Card', '/games/neuroneural-brainchop/index.html', 3, 0, 0],
  ['Breakout 1', 'auto-breakout-v0', 'Play Breakout 1 - Break the bricks!', 'Puzzle', '/games/auto-breakout-v0/index.html', 2, 0, 0],
  ['Breakout 2', 'auto-breakout-v1', 'Play Breakout 2 - Break the bricks!', 'Puzzle', '/games/auto-breakout-v1/index.html', 2, 0, 0],
  ['Breakout 3', 'auto-breakout-v2', 'Play Breakout 3 - Break the bricks!', 'Puzzle', '/games/auto-breakout-v2/index.html', 2, 0, 0],
  ['Breakout!', 'bradtraversy-vanillawebprojects', 'Play Breakout! - Break the bricks!', 'Puzzle', '/games/bradtraversy-vanillawebprojects/index.html', 4, 0, 0],
  ['Breakout!', 'solygambas-html-css-javascript-projects', 'Play Breakout! - Break the bricks!', 'Puzzle', '/games/solygambas-html-css-javascript-projects/index.html', 3, 0, 0],
  ['Brick Crusher', 'auto-brick-crusher', 'Play Brick Crusher - Puzzle game!', 'Puzzle', '/games/auto-brick-crusher/index.html', 1, 0, 0],
  ['Bubble Bobble', 'adriennedomingus-bubble_bobble', 'Play Bubble Bobble - Platformer game!', 'Platformer', '/games/adriennedomingus-bubble_bobble/index.html', 10, 0, 0],
  ['Bubble Shooter', 'auto-bubble-shooter', 'Play Bubble Shooter - Action shooter!', 'Shooting', '/games/auto-bubble-shooter/index.html', 1, 0, 0],
  ['Bullet Hell', 'auto-bullet-hell', 'Play Bullet Hell - Shooting game!', 'Shooting', '/games/auto-bullet-hell/index.html', 1, 0, 0],
  ['Camera', 'serratus-quaggaJS', 'Play Camera - Arcade game!', 'Arcade', '/games/serratus-quaggaJS/camera_example.html', 9, 0, 0],
  ['Canvas Cycle: True 8-bit Color Cycling with HTML5', 'jhuckaby-canvascycle', 'Play Canvas Cycle: True 8-bit Color Cycling with HTML5 - Platformer game!', 'Platformer', '/games/jhuckaby-canvascycle/index.html', 11, 0, 0],
  ['Captcha-checker', 'ayush7614-bundli-frontend', 'Play Captcha-checker - Arcade game!', 'Arcade', '/games/ayush7614-bundli-frontend/index.html', 2, 0, 0],
  ['Catan', 'geluso-catan', 'Play Catan - Puzzle game!', 'Puzzle', '/games/geluso-catan/index.html', 3, 0, 0],
  ['Cave Copter', 'fbn776-copter', 'Play Cave Copter - Arcade game!', 'Arcade', '/games/fbn776-copter/index.html', 2, 0, 0],
  ['cellauto.js', 'sanojian-cellauto', 'Play cellauto.js - Puzzle game!', 'Puzzle', '/games/sanojian-cellauto/index.html', 6, 0, 0],
  ['Cesium', 'Gaia3D-mago3djs', 'Play Cesium - Puzzle game!', 'Puzzle', '/games/Gaia3D-mago3djs/cesium.html', 4, 0, 0],
  ['Chair three js', 'nadiamariduena-3d-configurator-beginner1', 'Play Chair three js - 3D game!', '3D', '/games/nadiamariduena-3d-configurator-beginner1/index.html', 2, 0, 0],
  ['Checkers 1', 'auto-checkers-v0', 'Play Checkers 1 - Checkers game!', 'Board', '/games/auto-checkers-v0/index.html', 2, 0, 0],
  ['Checkers 2', 'auto-checkers-v1', 'Play Checkers 2 - Checkers game!', 'Board', '/games/auto-checkers-v1/index.html', 2, 0, 0],
  ['Checkers 3', 'auto-checkers-v2', 'Play Checkers 3 - Checkers game!', 'Board', '/games/auto-checkers-v2/index.html', 2, 0, 0],
  ['Checkers Net', 'btsan-checkersbot', 'Play Checkers Net - Checkers game!', 'Platformer', '/games/btsan-checkersbot/index.html', 6, 0, 0],
  ['Chess 1', 'auto-chess-v0', 'Play Chess 1 - Classic board game!', 'Board', '/games/auto-chess-v0/index.html', 2, 0, 0],
  ['Chess 2', 'auto-chess-v1', 'Play Chess 2 - Classic board game!', 'Board', '/games/auto-chess-v1/index.html', 2, 0, 0],
  ['Chess 3', 'auto-chess-v2', 'Play Chess 3 - Classic board game!', 'Board', '/games/auto-chess-v2/index.html', 2, 0, 0],
  ['Chess Master', 'auto-chess-master', 'Play Chess Master - Classic board game!', 'Board', '/games/auto-chess-master/index.html', 1, 0, 0],
  ['Chisimba Chisimba', 'chisimba-chisimba', 'Play Chisimba Chisimba - Racing game!', 'Racing', '/games/chisimba-chisimba/LICENCE.html', 1, 0, 0],
  ['ChrisChrisLoLo TamagotchiClone', 'ChrisChrisLoLo-tamagotchiClone', 'Play ChrisChrisLoLo TamagotchiClone - Arcade game!', 'Arcade', '/games/ChrisChrisLoLo-tamagotchiClone/index.html', 2, 0, 0],
  ['Cisco Talos Blog: Rigging compromise - RIG Exploit Kit', 'cybermonitor-apt-cybercriminal-campagin-collections', 'Play Cisco Talos Blog: Rigging compromise - RIG Exploit Kit - Puzzle game!', 'Puzzle', '/games/cybermonitor-apt-cybercriminal-campagin-collections/index.html', 2, 0, 0],
  ['Classic Pool Game', 'Bibi1205-2D-Classic-Pool-Game', 'Play Classic Pool Game - Arcade game!', 'Arcade', '/games/Bibi1205-2D-Classic-Pool-Game/index.html', 3, 0, 0],
  ['Classic Pool Game', 'henshmi-Classic-Pool-Game', 'Play Classic Pool Game - Arcade game!', 'Arcade', '/games/henshmi-Classic-Pool-Game/index.html', 3, 0, 0],
  ['Classic Snake', 'auto-classic-snake', 'Play Classic Snake - Classic snake arcade game!', 'Arcade', '/games/auto-classic-snake/index.html', 1, 0, 0],
  ['Cocos2d-html5 Hello World test', 'cocos2d-cocos2d-html5', 'Play Cocos2d-html5 Hello World test - Arcade game!', 'Arcade', '/games/cocos2d-cocos2d-html5/index.html', 3, 0, 0],
  ['Collection poster Maker', 'jeffersoncgo-CoverMaker', 'Play Collection poster Maker - Puzzle game!', 'Puzzle', '/games/jeffersoncgo-CoverMaker/index.html', 4, 0, 0],
  ['collision-2d examples', 'mreinstein-collision-2d', 'Play collision-2d examples - Arcade game!', 'Arcade', '/games/mreinstein-collision-2d/figures.html', 7, 0, 0],
  ['Color Match', 'auto-color-match', 'Play Color Match - Arcade game!', 'Arcade', '/games/auto-color-match/index.html', 1, 0, 0],
  ['Commit Mono. Neutral programming typeface.', 'eigilnikolajsen-commit-mono', 'Play Commit Mono. Neutral programming typeface. - Puzzle game!', 'Puzzle', '/games/eigilnikolajsen-commit-mono/index.html', 8, 0, 0],
  ['Connect Four', 'auto-connect-four', 'Play Connect Four - Connect four!', 'Board', '/games/auto-connect-four/index.html', 1, 0, 0],
  ['Connect Four 1', 'auto-connect4-v0', 'Play Connect Four 1 - Connect four!', 'Board', '/games/auto-connect4-v0/index.html', 2, 0, 0],
  ['Connect Four 2', 'auto-connect4-v1', 'Play Connect Four 2 - Connect four!', 'Board', '/games/auto-connect4-v1/index.html', 2, 0, 0],
  ['Connect Four 3', 'auto-connect4-v2', 'Play Connect Four 3 - Connect four!', 'Board', '/games/auto-connect4-v2/index.html', 2, 0, 0],
  ['Conservation of Energy • Physics Notebook', 'CasberryIndia-Physics-Notebook', 'Play Conservation of Energy • Physics Notebook - Puzzle game!', 'Puzzle', '/games/CasberryIndia-Physics-Notebook/conservation-of-energy.html', 12, 0, 0],
  ['Contact', 'ruuda-blog', 'Play Contact - 3D game!', '3D', '/games/ruuda-blog/contact.html', 10, 0, 0],
  ['Convex Conjugates', 'remilepriol-dualityviz', 'Play Convex Conjugates - Arcade game!', 'Arcade', '/games/remilepriol-dualityviz/index.html', 6, 0, 0],
  ['Conway Life Sim', 'auto-life-simulation', 'Play Conway Life Sim - Simulation game!', 'Simulation', '/games/auto-life-simulation/index.html', 1, 0, 0],
  ['Coquette', 'maryrosecook-coquette', 'Play Coquette - Puzzle game!', 'Puzzle', '/games/maryrosecook-coquette/index.html', 7, 0, 0],
  ['Cosmic Pong', 'auto-cosmic-pong', 'Play Cosmic Pong - Arcade game!', 'Arcade', '/games/auto-cosmic-pong/index.html', 1, 0, 0],
  ['crisp-game-lib', 'abagames-crisp-game-lib', 'Play crisp-game-lib - Arcade game!', 'Arcade', '/games/abagames-crisp-game-lib/index.html', 3, 0, 0],
  ['Croquet Jasmine (2004)', 'codefrau-jasmine', 'Play Croquet Jasmine (2004) - Platformer game!', 'Platformer', '/games/codefrau-jasmine/index.html', 10, 0, 0],
  ['Crossy Camp', 'woonseah-crossy-camp', 'Play Crossy Camp - Arcade game!', 'Arcade', '/games/woonseah-crossy-camp/index.html', 1, 0, 0],
  ['Crossy Road Game Clone', 'ejazahmed-dev-crossy-road-game-clone', 'Play Crossy Road Game Clone - Arcade game!', 'Arcade', '/games/ejazahmed-dev-crossy-road-game-clone/index.html', 3, 0, 0],
  ['Crossy Roads', 'saket-db-crossy-roads-game-main', 'Play Crossy Roads - Arcade game!', 'Arcade', '/games/saket-db-crossy-roads-game-main/index.html', 4, 0, 0],
  ['CRTFilter by Aka', 'Ichiaka-CRTFilter', 'Play CRTFilter by Aka - Racing game!', 'Racing', '/games/Ichiaka-CRTFilter/index.html', 4, 0, 0],
  ['CSS: pure css mockup', 'khan4019-front-end-Interview-Questions', 'Play CSS: pure css mockup - Puzzle game!', 'Puzzle', '/games/khan4019-front-end-Interview-Questions/css2.html', 24, 0, 0],
  ['Cube Jump 1', 'auto-cube-jump-v0', 'Play Cube Jump 1 - Platformer game!', 'Platformer', '/games/auto-cube-jump-v0/index.html', 2, 0, 0],
  ['Cube Jump 10', 'auto-cube-jump-v9', 'Play Cube Jump 10 - Platformer game!', 'Platformer', '/games/auto-cube-jump-v9/index.html', 2, 0, 0],
  ['Cube Jump 11', 'auto-cube-jump-v10', 'Play Cube Jump 11 - Platformer game!', 'Platformer', '/games/auto-cube-jump-v10/index.html', 2, 0, 0],
  ['Cube Jump 12', 'auto-cube-jump-v11', 'Play Cube Jump 12 - Platformer game!', 'Platformer', '/games/auto-cube-jump-v11/index.html', 2, 0, 0],
  ['Cube Jump 2', 'auto-cube-jump-v1', 'Play Cube Jump 2 - Platformer game!', 'Platformer', '/games/auto-cube-jump-v1/index.html', 2, 0, 0],
  ['Cube Jump 3', 'auto-cube-jump-v2', 'Play Cube Jump 3 - Platformer game!', 'Platformer', '/games/auto-cube-jump-v2/index.html', 2, 0, 0],
  ['Cube Jump 4', 'auto-cube-jump-v3', 'Play Cube Jump 4 - Platformer game!', 'Platformer', '/games/auto-cube-jump-v3/index.html', 2, 0, 0],
  ['Cube Jump 5', 'auto-cube-jump-v4', 'Play Cube Jump 5 - Platformer game!', 'Platformer', '/games/auto-cube-jump-v4/index.html', 2, 0, 0],
  ['Cube Jump 6', 'auto-cube-jump-v5', 'Play Cube Jump 6 - Platformer game!', 'Platformer', '/games/auto-cube-jump-v5/index.html', 2, 0, 0],
  ['Cube Jump 7', 'auto-cube-jump-v6', 'Play Cube Jump 7 - Platformer game!', 'Platformer', '/games/auto-cube-jump-v6/index.html', 2, 0, 0],
  ['Cube Jump 8', 'auto-cube-jump-v7', 'Play Cube Jump 8 - Platformer game!', 'Platformer', '/games/auto-cube-jump-v7/index.html', 2, 0, 0],
  ['Cube Jump 9', 'auto-cube-jump-v8', 'Play Cube Jump 9 - Platformer game!', 'Platformer', '/games/auto-cube-jump-v8/index.html', 2, 0, 0],
  ['Current Condition', 'consti-currentcondition', 'Play Current Condition - Puzzle game!', 'Puzzle', '/games/consti-currentcondition/index.html', 3, 0, 0],
  ['curtains.js', 'martinlaxenaire-curtainsjs', 'Play curtains.js - Card game!', 'Card', '/games/martinlaxenaire-curtainsjs/curtains-class.html', 19, 0, 0],
  ['Custom Logic', 'sharpie7-circuitjs1', 'Play Custom Logic - Puzzle game!', 'Puzzle', '/games/sharpie7-circuitjs1/customlogic.html', 13, 0, 0],
  ['D3-Celestial Starmap', 'ofrohn-d3-celestial', 'Play D3-Celestial Starmap - Puzzle game!', 'Puzzle', '/games/ofrohn-d3-celestial/planets-animation.html', 12, 0, 0],
  ['DarkFO', 'darkf-darkfo', 'Play DarkFO - 3D game!', '3D', '/games/darkf-darkfo/play.html', 8, 0, 0],
  ['Dashboard', 'puikinsh-Adminator-admin-dashboard', 'Play Dashboard - Arcade game!', 'Arcade', '/games/puikinsh-Adminator-admin-dashboard/index.html', 18, 0, 0],
  ['Dashboard 1 - Gentelella', 'ColorlibHQ-gentelella', 'Play Dashboard 1 - Gentelella - Puzzle game!', 'Puzzle', '/games/ColorlibHQ-gentelella/index.html', 40, 0, 0],
  ['DCF - Mathematical Formalization of Handshakeless Communication', 'ALH477-HydraMesh', 'Play DCF - Mathematical Formalization of Handshakeless Communication - Puzzle game!', 'Puzzle', '/games/ALH477-HydraMesh/dcf_mathematical_formalization.html', 4, 0, 0],
  ['Dead Valley', 'dmcinnes-dead-valley', 'Play Dead Valley - Puzzle game!', 'Puzzle', '/games/dmcinnes-dead-valley/index.html', 8, 0, 0],
  ['Demo - Steppe', 'ajbkr-Steppe', 'Play Demo - Steppe - Arcade game!', 'Arcade', '/games/ajbkr-Steppe/index.html', 3, 0, 0],
  ['Demo of complex text in canvas', 'WICG-html-in-canvas', 'Play Demo of complex text in canvas - Puzzle game!', 'Puzzle', '/games/WICG-html-in-canvas/complex-text.html', 6, 0, 0],
  ['Dgatewood ShapeCrush', 'dgatewood-ShapeCrush', 'Play Dgatewood ShapeCrush - Puzzle game!', 'Puzzle', '/games/dgatewood-ShapeCrush/index.html', 32, 0, 0],
  ['Displaying the canvas', 'eamonnzhang-learning-pixi', 'Play Displaying the canvas - Puzzle game!', 'Puzzle', '/games/eamonnzhang-learning-pixi/index.html', 1, 0, 0],
  ['Document', 'Reon90-redcube', 'Play Document - Platformer game!', 'Platformer', '/games/Reon90-redcube/index.html', 18, 0, 0],
  ['Documentation', 'lut0pia-raccoon', 'Play Documentation - Puzzle game!', 'Puzzle', '/games/lut0pia-raccoon/index.html', 2, 0, 0],
  ['Documentation for Platypus 5.5.0', 'sveinbjornt-Platypus', 'Play Documentation for Platypus 5.5.0 - Puzzle game!', 'Puzzle', '/games/sveinbjornt-Platypus/Documentation.html', 3, 0, 0],
  ['Dodger 1', 'auto-dodger-v0', 'Play Dodger 1 - Arcade game!', 'Arcade', '/games/auto-dodger-v0/index.html', 2, 0, 0],
  ['Dodger 2', 'auto-dodger-v1', 'Play Dodger 2 - Arcade game!', 'Arcade', '/games/auto-dodger-v1/index.html', 2, 0, 0],
  ['Dodger 3', 'auto-dodger-v2', 'Play Dodger 3 - Arcade game!', 'Arcade', '/games/auto-dodger-v2/index.html', 2, 0, 0],
  ['DOM Manipulation in JS', 'learning-zone-javascript-basics', 'Play DOM Manipulation in JS - 3D game!', '3D', '/games/learning-zone-javascript-basics/dom-manipulation.html', 11, 0, 0],
  ['Doodle Jump 1', 'auto-doodle-v0', 'Play Doodle Jump 1 - Platformer game!', 'Platformer', '/games/auto-doodle-v0/index.html', 2, 0, 0],
  ['Doodle Jump 2', 'auto-doodle-v1', 'Play Doodle Jump 2 - Platformer game!', 'Platformer', '/games/auto-doodle-v1/index.html', 2, 0, 0],
  ['Doodle Jump 3', 'auto-doodle-v2', 'Play Doodle Jump 3 - Platformer game!', 'Platformer', '/games/auto-doodle-v2/index.html', 2, 0, 0],
  ['draughts-draughts-github-io', 'draughts-draughts-github-io', 'Play draughts-draughts-github-io - Checkers game!', 'Puzzle', '/games/draughts-draughts-github-io/index.html', 47, 0, 0],
  ['DrawAFish.com', 'aldenhallak-fishes', 'Play DrawAFish.com - Puzzle game!', 'Puzzle', '/games/aldenhallak-fishes/index.html', 14, 0, 0],
  ['Drawing App', 'bradtraversy-50projects50days', 'Play Drawing App - Arcade game!', 'Arcade', '/games/bradtraversy-50projects50days/index.html', 2, 0, 0],
  ['Drawing App JavaScript', 'SudeepAcharjee-The-50-Front-end-Project', 'Play Drawing App JavaScript - Arcade game!', 'Arcade', '/games/SudeepAcharjee-The-50-Front-end-Project/index.html', 3, 0, 0],
  ['Duck Hunter', 'auto-duck-hunter', 'Play Duck Hunter - Arcade game!', 'Arcade', '/games/auto-duck-hunter/index.html', 1, 0, 0],
  ['Dungeon Crawler', 'auto-dungeon-crawler', 'Play Dungeon Crawler - RPG adventure!', 'RPG', '/games/auto-dungeon-crawler/index.html', 1, 0, 0],
  ['earth :: an animated map of global wind and weather', 'cambecc-earth', 'Play earth :: an animated map of global wind and weather - Racing game!', 'Racing', '/games/cambecc-earth/index.html', 10, 0, 0],
  ['EaselJS: API Test', 'createjs-easeljs', 'Play EaselJS: API Test - Platformer game!', 'Platformer', '/games/createjs-easeljs/index.html', 1, 0, 0],
  ['Ebisu', 'fasiha-ebisu', 'Play Ebisu - Puzzle game!', 'Puzzle', '/games/fasiha-ebisu/index.html', 9, 0, 0],
  ['ED-Board - 3D Galaxy map test', 'gbiobob-ED3D-Galaxy-Map', 'Play ED-Board - 3D Galaxy map test - 3D game!', '3D', '/games/gbiobob-ED3D-Galaxy-Map/demo_galnet.html', 6, 0, 0],
  ['Edge Not Found by Tom Hermans (@Auroriax)', 'auroriax-js13k-2020', 'Play Edge Not Found by Tom Hermans (@Auroriax) - Arcade game!', 'Arcade', '/games/auroriax-js13k-2020/index.html', 1, 0, 0],
  ['Emoji Width: Canvas vs DOM', 'chenglou-pretext', 'Play Emoji Width: Canvas vs DOM - Puzzle game!', 'Puzzle', '/games/chenglou-pretext/emoji-test.html', 6, 0, 0],
  ['Endless Runner', 'auto-endless-runner', 'Play Endless Runner - Arcade game!', 'Arcade', '/games/auto-endless-runner/index.html', 1, 0, 0],
  ['Entropy - Breakout Game', 'city41-breakouts', 'Play Entropy - Breakout Game - Break the bricks!', 'Puzzle', '/games/city41-breakouts/index.html', 2, 0, 0],
  ['Essential JavaScript Links', 'starandtina-Essential-JavaScript-Links', 'Play Essential JavaScript Links - Puzzle game!', 'Puzzle', '/games/starandtina-Essential-JavaScript-Links/index.html', 4, 0, 0],
  ['Events', 'NorthwoodsSoftware-GoJS', 'Play Events - Puzzle game!', 'Puzzle', '/games/NorthwoodsSoftware-GoJS/index.html', 1, 0, 0],
  ['Everest Flight Simulator', 'mpaccione-everest_flight_sim', 'Play Everest Flight Simulator - 3D game!', '3D', '/games/mpaccione-everest_flight_sim/index.html', 2, 0, 0],
  ['FAS envelopes type', 'grz0zrg-fas', 'Play FAS envelopes type - Arcade game!', 'Arcade', '/games/grz0zrg-fas/envs.html', 1, 0, 0],
  ['Fechin Reference', 'fechin-reference', 'Play Fechin Reference - Puzzle game!', 'Puzzle', '/games/fechin-reference/index.html', 1, 0, 0],
  ['fiK', 'lo-th-fullik', 'Play fiK - Puzzle game!', 'Puzzle', '/games/lo-th-fullik/index.html', 6, 0, 0],
  ['Fire Emblem: Chronicles of the Abyss', 'chessmasterhong-WaterEmblem', 'Play Fire Emblem: Chronicles of the Abyss - Puzzle game!', 'Puzzle', '/games/chessmasterhong-WaterEmblem/index.html', 2, 0, 0],
  ['Flappy Bird', 'auto-flappy-bird-mnttmliu', 'Play Flappy Bird - Flying challenge!', 'Arcade', '/games/auto-flappy-bird-mnttmliu/index.html', 2, 0, 0],
  ['Flappy Bird 1', 'auto-flappy-v0', 'Play Flappy Bird 1 - Flying challenge!', 'Arcade', '/games/auto-flappy-v0/index.html', 2, 0, 0],
  ['Flappy Bird 2', 'auto-flappy-v1', 'Play Flappy Bird 2 - Flying challenge!', 'Arcade', '/games/auto-flappy-v1/index.html', 2, 0, 0],
  ['Flappy Bird 3', 'auto-flappy-v2', 'Play Flappy Bird 3 - Flying challenge!', 'Arcade', '/games/auto-flappy-v2/index.html', 2, 0, 0],
  ['Flocking Birds', 'auto-flocking-simulation', 'Play Flocking Birds - Arcade game!', 'Arcade', '/games/auto-flocking-simulation/index.html', 1, 0, 0],
  ['For The Swarm!', 'PorkShoulderHolder-morph', 'Play For The Swarm! - Simulation game!', 'Simulation', '/games/PorkShoulderHolder-morph/scribble.html', 6, 0, 0],
  ['FPS3 - Multiplayer First Person Shooter game', 'Parking-Master-FPS3', 'Play FPS3 - Multiplayer First Person Shooter game - Action shooter!', 'Puzzle', '/games/Parking-Master-FPS3/index.html', 16, 0, 0],
  ['Frogger 1', 'auto-frogger-v0', 'Play Frogger 1 - Platformer game!', 'Platformer', '/games/auto-frogger-v0/index.html', 2, 0, 0],
  ['Frogger 2', 'auto-frogger-v1', 'Play Frogger 2 - Platformer game!', 'Platformer', '/games/auto-frogger-v1/index.html', 2, 0, 0],
  ['Frogger 3', 'auto-frogger-v2', 'Play Frogger 3 - Platformer game!', 'Platformer', '/games/auto-frogger-v2/index.html', 2, 0, 0],
  ['Frozen Cookies', 'Icehawk78-FrozenCookies', 'Play Frozen Cookies - 3D game!', '3D', '/games/Icehawk78-FrozenCookies/index.html', 14, 0, 0],
  ['gabrielecirulli-2048', 'gabrielecirulli-2048', 'Play gabrielecirulli-2048 - Number puzzle game!', 'Puzzle', '/games/gabrielecirulli-2048/index.html', 6, 0, 0],
  ['Galaga', 'hoorayimhelping-galaga5', 'Play Galaga - Shooting game!', 'Shooting', '/games/hoorayimhelping-galaga5/index.html', 13, 0, 0],
  ['Galaga 1', 'auto-galaga-v0', 'Play Galaga 1 - Shooting game!', 'Shooting', '/games/auto-galaga-v0/index.html', 2, 0, 0],
  ['Galaga 2', 'auto-galaga-v1', 'Play Galaga 2 - Shooting game!', 'Shooting', '/games/auto-galaga-v1/index.html', 2, 0, 0],
  ['Galaga 3', 'auto-galaga-v2', 'Play Galaga 3 - Shooting game!', 'Shooting', '/games/auto-galaga-v2/index.html', 2, 0, 0],
  ['Galaga Blaster', 'auto-galaga-blaster', 'Play Galaga Blaster - Shooting game!', 'Shooting', '/games/auto-galaga-blaster/index.html', 1, 0, 0],
  ['Game of Life 1', 'auto-life-v0', 'Play Game of Life 1 - Arcade game!', 'Arcade', '/games/auto-life-v0/index.html', 2, 0, 0],
  ['Game of Life 2', 'auto-life-v1', 'Play Game of Life 2 - Arcade game!', 'Arcade', '/games/auto-life-v1/index.html', 2, 0, 0],
  ['Game of Life 3', 'auto-life-v2', 'Play Game of Life 3 - Arcade game!', 'Arcade', '/games/auto-life-v2/index.html', 2, 0, 0],
  ['GameSphere.', 'chromegaming-gamesphere', 'Play GameSphere. - Puzzle game!', 'Puzzle', '/games/chromegaming-gamesphere/index.html', 1, 0, 0],
  ['Gem Battle', 'jeffdam-gem_battle', 'Play Gem Battle - Puzzle game!', 'Puzzle', '/games/jeffdam-gem_battle/index.html', 4, 0, 0],
  ['Gem Collector', 'auto-gem-collector', 'Play Gem Collector - Arcade game!', 'Arcade', '/games/auto-gem-collector/index.html', 1, 0, 0],
  ['GEOWars', 'thirdcommand-geowars', 'Play GEOWars - Puzzle game!', 'Puzzle', '/games/thirdcommand-geowars/index.html', 12, 0, 0],
  ['Ghost Game', 'omarshehata-i-spy-a-ghost', 'Play Ghost Game - Arcade game!', 'Arcade', '/games/omarshehata-i-spy-a-ghost/index.html', 3, 0, 0],
  ['GitHubDragonFly\'s Website', 'GitHubDragonFly-GitHubDragonFly.github.io', 'Play GitHubDragonFly\'s Website - Puzzle game!', 'Puzzle', '/games/GitHubDragonFly-GitHubDragonFly.github.io/index.html', 5, 0, 0],
  ['Glacambre Firenvim', 'glacambre-firenvim', 'Play Glacambre Firenvim - Arcade game!', 'Arcade', '/games/glacambre-firenvim/index.html', 4, 0, 0],
  ['Golden Sun Engine - HTML5', 'jjppof-goldensun_html5', 'Play Golden Sun Engine - HTML5 - Puzzle game!', 'Puzzle', '/games/jjppof-goldensun_html5/index.html', 10, 0, 0],
  ['Google C++ Style Guide', 'google-styleguide', 'Play Google C++ Style Guide - Puzzle game!', 'Puzzle', '/games/google-styleguide/cppguide.html', 24, 0, 0],
  ['gotoв!', 'fpereiro-gotoB', 'Play gotoв! - Puzzle game!', 'Puzzle', '/games/fpereiro-gotoB/test.html', 6, 0, 0],
  ['Govt Policies and Schemes', 'Ishaan28malik-Hacktoberfest-2024', 'Play Govt Policies and Schemes - Card game!', 'Card', '/games/Ishaan28malik-Hacktoberfest-2024/project.html', 8, 0, 0],
  ['Gracia Player', 'gracia-labs-web-sdk', 'Play Gracia Player - Puzzle game!', 'Puzzle', '/games/gracia-labs-web-sdk/index.html', 8, 0, 0],
  ['Gravity Balls', 'auto-gravity-balls', 'Play Gravity Balls - Simulation game!', 'Simulation', '/games/auto-gravity-balls/index.html', 1, 0, 0],
  ['GreenSock Animation Platform (GSAP) Speed Test', 'julianshapiro-velocity', 'Play GreenSock Animation Platform (GSAP) Speed Test - Puzzle game!', 'Puzzle', '/games/julianshapiro-velocity/GreenSock Animation Platform (GSAP) Speed Test.html', 1, 0, 0],
  ['Grid Physics Example', 'nkholski-phaser-grid-physics', 'Play Grid Physics Example - Simulation game!', 'Simulation', '/games/nkholski-phaser-grid-physics/index.html', 1, 0, 0],
  ['Growing graphs', 'znah-graphs', 'Play Growing graphs - Puzzle game!', 'Puzzle', '/games/znah-graphs/index.html', 6, 0, 0],
  ['GVRM', 'naruya-gaussian-vrm', 'Play GVRM - Puzzle game!', 'Puzzle', '/games/naruya-gaussian-vrm/index.html', 11, 0, 0],
  ['Handtrack.js : A library for prototyping realtime handtracking in the browser.', 'victordibia-handtrack.js', 'Play Handtrack.js : A library for prototyping realtime handtracking in the browser. - Racing game!', 'Racing', '/games/victordibia-handtrack.js/index.html', 2, 0, 0],
  ['Hangman', 'auto-hanging-word', 'Play Hangman - Puzzle game!', 'Puzzle', '/games/auto-hanging-word/index.html', 1, 0, 0],
  ['Hauberk', 'munificent-hauberk', 'Play Hauberk - Puzzle game!', 'Puzzle', '/games/munificent-hauberk/getting-started.html', 15, 0, 0],
  ['headings', 'thekicker-harvard-cs50', 'Play headings - 3D game!', '3D', '/games/thekicker-harvard-cs50/headings.html', 45, 0, 0],
  ['Hello Anigif!', 'yaronn-GifW00t', 'Play Hello Anigif! - Arcade game!', 'Arcade', '/games/yaronn-GifW00t/simple.html', 6, 0, 0],
  ['Hello canvas world :D', 'medram-3Din2DCanvas', 'Play Hello canvas world :D - Arcade game!', 'Arcade', '/games/medram-3Din2DCanvas/index.html', 21, 0, 0],
  ['Hershey Font Lab', 'golanlevin-p5-single-line-font-resources', 'Play Hershey Font Lab - Arcade game!', 'Arcade', '/games/golanlevin-p5-single-line-font-resources/index.html', 10, 0, 0],
  ['HexGL by BKcore', 'bkcore-hexgl', 'Play HexGL by BKcore - Racing game!', 'Racing', '/games/bkcore-hexgl/index.html', 1, 0, 0],
  ['Hextris', 'hextris-hextris', 'Play Hextris - Puzzle game!', 'Puzzle', '/games/hextris-hextris/index.html', 6, 0, 0],
  ['Hollow Knight', 'TinTinWinata-hollow-knight-js', 'Play Hollow Knight - Arcade game!', 'Arcade', '/games/TinTinWinata-hollow-knight-js/game.html', 6, 0, 0],
  ['HTML5 Bombergirl', 'mattskala-html5-bombergirl', 'Play HTML5 Bombergirl - Racing game!', 'Racing', '/games/mattskala-html5-bombergirl/index.html', 5, 0, 0],
  ['HTML5 Word Cloud', 'timdream-wordcloud', 'Play HTML5 Word Cloud - Puzzle game!', 'Puzzle', '/games/timdream-wordcloud/index.html', 1, 0, 0],
  ['Hue Jumper', 'KilledByAPixel-HueJumper2k', 'Play Hue Jumper - Arcade game!', 'Arcade', '/games/KilledByAPixel-HueJumper2k/index.html', 6, 0, 0],
  ['Hwatheod Gnubg Web', 'hwatheod-gnubg-web', 'Play Hwatheod Gnubg Web - Board game!', 'Board', '/games/hwatheod-gnubg-web/gnubg_web.html', 5, 0, 0],
  ['Ice Breaker', 'auto-icebreaker', 'Play Ice Breaker - Puzzle game!', 'Puzzle', '/games/auto-icebreaker/index.html', 1, 0, 0],
  ['Icon-Architecture/16/Arch_Amazon-CloudWatch_16', 'foundationagents-metagpt', 'Play Icon-Architecture/16/Arch_Amazon-CloudWatch_16 - Puzzle game!', 'Puzzle', '/games/foundationagents-metagpt/index.html', 1, 0, 0],
  ['index - pixelbutler', 'pixelbutler-pixelbutler', 'Play index - pixelbutler - 3D game!', '3D', '/games/pixelbutler-pixelbutler/index.html', 7, 0, 0],
  ['Jaammees Racer', 'jaammees-racer', 'Play Jaammees Racer - Racing challenge!', 'Racing', '/games/jaammees-racer/dev.html', 4, 0, 0],
  ['Javascript Physics Libraries', 'cmann1-javascript-physics-library-tests', 'Play Javascript Physics Libraries - Simulation game!', 'Simulation', '/games/cmann1-javascript-physics-library-tests/index.html', 2, 0, 0],
  ['Javascript Platformer', 'jakesgordon-javascript-tiny-platformer', 'Play Javascript Platformer - Platform adventure!', 'Puzzle', '/games/jakesgordon-javascript-tiny-platformer/index.html', 7, 0, 0],
  ['Javascript Racer - v1 (straight)', 'jakesgordon-javascript-racer', 'Play Javascript Racer - v1 (straight) - Racing challenge!', 'Racing', '/games/jakesgordon-javascript-racer/v1.straight.html', 11, 0, 0],
  ['Javascript Tetris', 'jakesgordon-javascript-tetris', 'Play Javascript Tetris - Block puzzle challenge!', 'Puzzle', '/games/jakesgordon-javascript-tetris/index.html', 5, 0, 0],
  ['JavaScript Tetris', 'melcor76-js-tetris', 'Play JavaScript Tetris - Block puzzle challenge!', 'Puzzle', '/games/melcor76-js-tetris/index.html', 1, 0, 0],
  ['JavaScript Voronoi', 'gregross-javascript-voronoi', 'Play JavaScript Voronoi - 3D game!', '3D', '/games/gregross-javascript-voronoi/googleVizApi.html', 3, 0, 0],
  ['Jelly Break', 'auto-jelly-break', 'Play Jelly Break - Arcade game!', 'Arcade', '/games/auto-jelly-break/index.html', 1, 0, 0],
  ['Johnny Castaway', 'xesf-castaway', 'Play Johnny Castaway - Puzzle game!', 'Puzzle', '/games/xesf-castaway/index.html', 3, 0, 0],
  ['JoltPhysics.js demos', 'jrouwe-JoltPhysics.js', 'Play JoltPhysics.js demos - Puzzle game!', 'Puzzle', '/games/jrouwe-JoltPhysics.js/index.html', 28, 0, 0],
  ['JS car', 'oseiskar-js-car', 'Play JS car - Racing challenge!', 'Racing', '/games/oseiskar-js-car/index.html', 5, 0, 0],
  ['JS ScummVM', 'mutle-jsscummvm', 'Play JS ScummVM - Arcade game!', 'Arcade', '/games/mutle-jsscummvm/index.html', 3, 0, 0],
  ['JS TinyRenderer', 'ccajas-JS-TinyRenderer', 'Play JS TinyRenderer - Arcade game!', 'Arcade', '/games/ccajas-JS-TinyRenderer/index.html', 7, 0, 0],
  ['jsOrrery - Javascript Solar System Simulator', 'mgvez-jsorrery', 'Play jsOrrery - Javascript Solar System Simulator - Platformer game!', 'Platformer', '/games/mgvez-jsorrery/index.html', 2, 0, 0],
  ['jssm — JavaScript State Machines Made Easy', 'stonecypher-jssm', 'Play jssm — JavaScript State Machines Made Easy - Puzzle game!', 'Puzzle', '/games/stonecypher-jssm/index.html', 7, 0, 0],
  ['Juj Wasm_webgpu', 'juj-wasm_webgpu', 'Play Juj Wasm_webgpu - Puzzle game!', 'Puzzle', '/games/juj-wasm_webgpu/shell.html', 3, 0, 0],
  ['Just Another Corona Virus World Map', 'raphaellepuschitz-SVG-World-Map', 'Play Just Another Corona Virus World Map - Arcade game!', 'Arcade', '/games/raphaellepuschitz-SVG-World-Map/corona-world-map.html', 10, 0, 0],
  ['Kingdom Defense', 'auto-kingdom-defense', 'Play Kingdom Defense - Arcade game!', 'Arcade', '/games/auto-kingdom-defense/index.html', 1, 0, 0],
  ['Koala hacker news', 'zutjoe-koalahackernews', 'Play Koala hacker news - Puzzle game!', 'Puzzle', '/games/zutjoe-koalahackernews/index.html', 7, 0, 0],
  ['Kodezi Chronos Performance Visualization', 'Kodezi-Chronos', 'Play Kodezi Chronos Performance Visualization - Card game!', 'Card', '/games/Kodezi-Chronos/performance_chart.html', 1, 0, 0],
  ['Kosmos', 'judnich-kosmos', 'Play Kosmos - Puzzle game!', 'Puzzle', '/games/judnich-kosmos/index.html', 5, 0, 0],
  ['L👀K — AI-Powered Demo Videos', 'nirholas-LooK', 'Play L👀K — AI-Powered Demo Videos - Puzzle game!', 'Puzzle', '/games/nirholas-LooK/index.html', 6, 0, 0],
  ['Labyrinth', 'fossasia-labyrinth', 'Play Labyrinth - Puzzle game!', 'Puzzle', '/games/fossasia-labyrinth/index.html', 10, 0, 0],
  ['Laser Maze', 'auto-laser-maze', 'Play Laser Maze - Arcade game!', 'Arcade', '/games/auto-laser-maze/index.html', 1, 0, 0],
  ['Leapmotion Leap Three Camera Controls', 'leapmotion-Leap-Three-Camera-Controls', 'Play Leapmotion Leap Three Camera Controls - Puzzle game!', 'Puzzle', '/games/leapmotion-Leap-Three-Camera-Controls/index.html', 4, 0, 0],
  ['Lenia', 'Chakazul-Lenia', 'Play Lenia - Puzzle game!', 'Puzzle', '/games/Chakazul-Lenia/Lenia.html', 2, 0, 0],
  ['Lights Out 1', 'auto-lights-out-v0', 'Play Lights Out 1 - Arcade game!', 'Arcade', '/games/auto-lights-out-v0/index.html', 2, 0, 0],
  ['Lights Out 2', 'auto-lights-out-v1', 'Play Lights Out 2 - Arcade game!', 'Arcade', '/games/auto-lights-out-v1/index.html', 2, 0, 0],
  ['Lights Out 3', 'auto-lights-out-v2', 'Play Lights Out 3 - Arcade game!', 'Arcade', '/games/auto-lights-out-v2/index.html', 2, 0, 0],
  ['Liquid Labs', 'lo-th-Liquid.lab', 'Play Liquid Labs - Racing game!', 'Racing', '/games/lo-th-Liquid.lab/index.html', 3, 0, 0],
  ['LocalMind — Private AI Chat in Your Browser', 'naklitechie-localmind', 'Play LocalMind — Private AI Chat in Your Browser - Puzzle game!', 'Puzzle', '/games/naklitechie-localmind/index.html', 1, 0, 0],
  ['Lysdexic Audio Jweb Object Detection', 'lysdexic-audio-jweb-object-detection', 'Play Lysdexic Audio Jweb Object Detection - Arcade game!', 'Arcade', '/games/lysdexic-audio-jweb-object-detection/jweb-object-detection.html', 3, 0, 0],
  ['Mafik Libcolony', 'mafik-libcolony', 'Play Mafik Libcolony - Arcade game!', 'Arcade', '/games/mafik-libcolony/demo.html', 8, 0, 0],
  ['Mahjong', 'pomax-mahjong', 'Play Mahjong - Tile matching!', 'Puzzle', '/games/pomax-mahjong/index.html', 4, 0, 0],
  ['Map Tests', 'englercj-phaser-tiled', 'Play Map Tests - Arcade game!', 'Arcade', '/games/englercj-phaser-tiled/index.html', 2, 0, 0],
  ['Marjo Ballabani', 'marjoballabani-marjoballabani-me', 'Play Marjo Ballabani - Puzzle game!', 'Puzzle', '/games/marjoballabani-marjoballabani-me/index.html', 8, 0, 0],
  ['Marjo Ballabani', 'marjoballabani-marjoballabani.me', 'Play Marjo Ballabani - Puzzle game!', 'Puzzle', '/games/marjoballabani-marjoballabani.me/index.html', 10, 0, 0],
  ['Master web development', 'iamrahulmahato-master-web-development', 'Play Master web development - Puzzle game!', 'Puzzle', '/games/iamrahulmahato-master-web-development/index.html', 1, 0, 0],
  ['Match 3 Gems', 'auto-match3-gems', 'Play Match 3 Gems - Arcade game!', 'Arcade', '/games/auto-match3-gems/index.html', 1, 0, 0],
  ['Maze of Death - Test Client', 'Codera101-Maze-of-Death', 'Play Maze of Death - Test Client - Puzzle game!', 'Puzzle', '/games/Codera101-Maze-of-Death/test-client.html', 5, 0, 0],
  ['Maze Runner', 'auto-maze-runner', 'Play Maze Runner - Arcade game!', 'Arcade', '/games/auto-maze-runner/index.html', 1, 0, 0],
  ['MCMC Interactive Gallery', 'chi-feng-mcmc-demo', 'Play MCMC Interactive Gallery - Puzzle game!', 'Puzzle', '/games/chi-feng-mcmc-demo/app.html', 4, 0, 0],
  ['medium editor', 'yabwe-medium-editor', 'Play medium editor - 3D game!', '3D', '/games/yabwe-medium-editor/static-toolbar.html', 16, 0, 0],
  ['Mega Buster', 'auto-mega-buster', 'Play Mega Buster - Arcade game!', 'Arcade', '/games/auto-mega-buster/index.html', 1, 0, 0],
  ['Memory Master', 'auto-memory-master', 'Play Memory Master - Arcade game!', 'Arcade', '/games/auto-memory-master/index.html', 1, 0, 0],
  ['Memory Match', 'auto-memory-match-mnttmliw', 'Play Memory Match - Arcade game!', 'Arcade', '/games/auto-memory-match-mnttmliw/index.html', 2, 0, 0],
  ['Memory Match 1', 'auto-memory-v0', 'Play Memory Match 1 - Arcade game!', 'Arcade', '/games/auto-memory-v0/index.html', 2, 0, 0],
  ['Memory Match 2', 'auto-memory-v1', 'Play Memory Match 2 - Arcade game!', 'Arcade', '/games/auto-memory-v1/index.html', 2, 0, 0],
  ['Memory Match 3', 'auto-memory-v2', 'Play Memory Match 3 - Arcade game!', 'Arcade', '/games/auto-memory-v2/index.html', 2, 0, 0],
  ['Mermaids of Lake Minnetonka 🧜‍♀️🌊', 'AaronCWacker-Yggdrasil', 'Play Mermaids of Lake Minnetonka 🧜‍♀️🌊 - Puzzle game!', 'Puzzle', '/games/AaronCWacker-Yggdrasil/index.html', 28, 0, 0],
  ['Metal Reviews, News, Blogs, Interviews and Community', 'PuerkitoBio-goquery', 'Play Metal Reviews, News, Blogs, Interviews and Community - Puzzle game!', 'Puzzle', '/games/PuerkitoBio-goquery/metalreview.html', 6, 0, 0],
  ['Microsimulation of Traffic Flow: Onramp', 'movsim-traffic-simulation-de', 'Play Microsimulation of Traffic Flow: Onramp - Racing game!', 'Racing', '/games/movsim-traffic-simulation-de/index.html', 81, 0, 0],
  ['Minesweeper 1', 'auto-minesweeper-v0', 'Play Minesweeper 1 - Arcade game!', 'Arcade', '/games/auto-minesweeper-v0/index.html', 2, 0, 0],
  ['Minesweeper 2', 'auto-minesweeper-v1', 'Play Minesweeper 2 - Arcade game!', 'Arcade', '/games/auto-minesweeper-v1/index.html', 2, 0, 0],
  ['Minesweeper 3', 'auto-minesweeper-v2', 'Play Minesweeper 3 - Arcade game!', 'Arcade', '/games/auto-minesweeper-v2/index.html', 2, 0, 0],
  ['Minesweeper Pro', 'auto-minesweeper-pro', 'Play Minesweeper Pro - Arcade game!', 'Arcade', '/games/auto-minesweeper-pro/index.html', 1, 0, 0],
  ['MINIPUNK', 'codyebberson-js13k-minipunk', 'Play MINIPUNK - Racing game!', 'Racing', '/games/codyebberson-js13k-minipunk/index.html', 5, 0, 0],
  ['Mixed Traffic Flow', 'MTGermany-mixedTraffic', 'Play Mixed Traffic Flow - Arcade game!', 'Arcade', '/games/MTGermany-mixedTraffic/index.html', 9, 0, 0],
  ['Mlc Ai Web Stable Diffusion', 'mlc-ai-web-stable-diffusion', 'Play Mlc Ai Web Stable Diffusion - Arcade game!', 'Arcade', '/games/mlc-ai-web-stable-diffusion/stable_diffusion.html', 4, 0, 0],
  ['Mooncraft', 'engineersneedart-mooncraft2000', 'Play Mooncraft - Puzzle game!', 'Puzzle', '/games/engineersneedart-mooncraft2000/index.html', 23, 0, 0],
  ['Moonの小屋', 'monthpity-moon-room', 'Play Moonの小屋 - Puzzle game!', 'Puzzle', '/games/monthpity-moon-room/index.html', 12, 0, 0],
  ['Moto Cross', 'auto-moto-cross', 'Play Moto Cross - Racing game!', 'Racing', '/games/auto-moto-cross/index.html', 1, 0, 0],
  ['My first three.js app', 'goit10042022-bollu', 'Play My first three.js app - Puzzle game!', 'Puzzle', '/games/goit10042022-bollu/three.html', 7, 0, 0],
  ['Ncase Wbwwb', 'ncase-wbwwb', 'Play Ncase Wbwwb - Puzzle game!', 'Puzzle', '/games/ncase-wbwwb/index.html', 3, 0, 0],
  ['Neon Racer', 'auto-neon-racer', 'Play Neon Racer - Racing challenge!', 'Racing', '/games/auto-neon-racer/index.html', 1, 0, 0],
  ['Neon Snake', 'auto-neon-snake', 'Play Neon Snake - Classic snake arcade game!', 'Arcade', '/games/auto-neon-snake/index.html', 1, 0, 0],
  ['NetCraft', 'satoshinm-NetCraft', 'Play NetCraft - Puzzle game!', 'Puzzle', '/games/satoshinm-NetCraft/shell.html', 3, 0, 0],
  ['Nicoptere Raymarching For THREE', 'nicoptere-raymarching-for-THREE', 'Play Nicoptere Raymarching For THREE - 3D game!', '3D', '/games/nicoptere-raymarching-for-THREE/index.html', 13, 0, 0],
  ['Night Shooter', 'auto-night-shooter', 'Play Night Shooter - Action shooter!', 'Shooting', '/games/auto-night-shooter/index.html', 1, 0, 0],
  ['NINJHAX - 3DS Homebrew Exploit', 'smealum-ninjhax', 'Play NINJHAX - 3DS Homebrew Exploit - Puzzle game!', 'Puzzle', '/games/smealum-ninjhax/index.html', 4, 0, 0],
  ['nomnoml', 'skanaar-nomnoml', 'Play nomnoml - Card game!', 'Card', '/games/skanaar-nomnoml/index.html', 12, 0, 0],
  ['noulith', 'betaveros-noulith', 'Play noulith - Puzzle game!', 'Puzzle', '/games/betaveros-noulith/index.html', 8, 0, 0],
  ['nwMAME', 'ozguncagri-nwMAME', 'Play nwMAME - 3D game!', '3D', '/games/ozguncagri-nwMAME/index.html', 4, 0, 0],
  ['Octave bands frequency distribution', 'hvianna-audioMotion-analyzer', 'Play Octave bands frequency distribution - Puzzle game!', 'Puzzle', '/games/hvianna-audioMotion-analyzer/octave-bands-viewer.html', 7, 0, 0],
  ['Oimo.js', 'lo-th-Oimo.js', 'Play Oimo.js - 3D game!', '3D', '/games/lo-th-Oimo.js/index.html', 6, 0, 0],
  ['Oimo.js Basic', 'lo-th-oimo-js', 'Play Oimo.js Basic - Simulation game!', 'Simulation', '/games/lo-th-oimo-js/test_basic.html', 10, 0, 0],
  ['Olive.c', 'tsoding-olive.c', 'Play Olive.c - 3D game!', '3D', '/games/tsoding-olive.c/index.html', 3, 0, 0],
  ['Open Optical Designer', 'alexbock-open-optical-designer', 'Play Open Optical Designer - Arcade game!', 'Arcade', '/games/alexbock-open-optical-designer/index.html', 5, 0, 0],
  ['openOutpaint 🐠', 'zero01101-openOutpaint', 'Play openOutpaint 🐠 - 3D game!', '3D', '/games/zero01101-openOutpaint/index.html', 9, 0, 0],
  ['OpHog', 'adam13531-ophog', 'Play OpHog - Simulation game!', 'Simulation', '/games/adam13531-ophog/index.html', 16, 0, 0],
  ['P2P Bomberman', 'internaut-p2p-bomberman', 'Play P2P Bomberman - Arcade game!', 'Arcade', '/games/internaut-p2p-bomberman/game.html', 2, 0, 0],
  ['Pac-Man', 'masonicgit-pacman', 'Play Pac-Man - Arcade game!', 'Arcade', '/games/masonicgit-pacman/index.html', 13, 0, 0],
  ['Pac-Man 1', 'auto-pacman-v0', 'Play Pac-Man 1 - Arcade game!', 'Arcade', '/games/auto-pacman-v0/index.html', 2, 0, 0],
  ['Pac-Man 2', 'auto-pacman-v1', 'Play Pac-Man 2 - Arcade game!', 'Arcade', '/games/auto-pacman-v1/index.html', 2, 0, 0],
  ['Pac-Man 3', 'auto-pacman-v2', 'Play Pac-Man 3 - Arcade game!', 'Arcade', '/games/auto-pacman-v2/index.html', 2, 0, 0],
  ['Pacman in HTML 5 Canvas', 'platzhersh-pacman-canvas', 'Play Pacman in HTML 5 Canvas - Classic arcade game!', 'Puzzle', '/games/platzhersh-pacman-canvas/index.html', 1, 0, 0],
  ['Particle Sim 1', 'auto-particles-v0', 'Play Particle Sim 1 - Simulation game!', 'Simulation', '/games/auto-particles-v0/index.html', 2, 0, 0],
  ['Particle Sim 2', 'auto-particles-v1', 'Play Particle Sim 2 - Simulation game!', 'Simulation', '/games/auto-particles-v1/index.html', 2, 0, 0],
  ['Particle Sim 3', 'auto-particles-v2', 'Play Particle Sim 3 - Simulation game!', 'Simulation', '/games/auto-particles-v2/index.html', 2, 0, 0],
  ['Particle Storm', 'auto-particle-storm', 'Play Particle Storm - Simulation game!', 'Simulation', '/games/auto-particle-storm/index.html', 1, 0, 0],
  ['particles.js', 'VincentGarreau-particles.js', 'Play particles.js - Simulation game!', 'Simulation', '/games/VincentGarreau-particles.js/index.html', 2, 0, 0],
  ['Peasy', 'chaosim-peasy', 'Play Peasy - Puzzle game!', 'Puzzle', '/games/chaosim-peasy/nonmodularpeasy.html', 6, 0, 0],
  ['Peg Solitaire 1', 'auto-peg-solitaire-v0', 'Play Peg Solitaire 1 - Card game!', 'Card', '/games/auto-peg-solitaire-v0/index.html', 2, 0, 0],
  ['Peg Solitaire 2', 'auto-peg-solitaire-v1', 'Play Peg Solitaire 2 - Card game!', 'Card', '/games/auto-peg-solitaire-v1/index.html', 2, 0, 0],
  ['Peg Solitaire 3', 'auto-peg-solitaire-v2', 'Play Peg Solitaire 3 - Card game!', 'Card', '/games/auto-peg-solitaire-v2/index.html', 2, 0, 0],
  ['phoria.js', 'kevinroast-phoria.js', 'Play phoria.js - Puzzle game!', 'Puzzle', '/games/kevinroast-phoria.js/index.html', 31, 0, 0],
  ['PhysicsRus', 'juhl-physicsRus', 'Play PhysicsRus - Racing game!', 'Racing', '/games/juhl-physicsRus/play.html', 3, 0, 0],
  ['PhysX Test', 'fabmax-physx-js-webidl', 'Play PhysX Test - Puzzle game!', 'Puzzle', '/games/fabmax-physx-js-webidl/helloworld.html', 4, 0, 0],
  ['Picture to colour QR code converter', 'xyzzy-qrpicture', 'Play Picture to colour QR code converter - Card game!', 'Card', '/games/xyzzy-qrpicture/index.html', 8, 0, 0],
  ['Pinball Classic', 'auto-pinball-classic', 'Play Pinball Classic - Arcade game!', 'Arcade', '/games/auto-pinball-classic/index.html', 1, 0, 0],
  ['Pixel Adventure', 'auto-pixel-adventure', 'Play Pixel Adventure - Platformer game!', 'Platformer', '/games/auto-pixel-adventure/index.html', 1, 0, 0],
  ['Pixel Forge', 'cochranblock-pixel-forge', 'Play Pixel Forge - Puzzle game!', 'Puzzle', '/games/cochranblock-pixel-forge/index.html', 3, 0, 0],
  ['Platformer 1', 'auto-platformer-v0', 'Play Platformer 1 - Platform adventure!', 'Platformer', '/games/auto-platformer-v0/index.html', 2, 0, 0],
  ['Platformer 2', 'auto-platformer-v1', 'Play Platformer 2 - Platform adventure!', 'Platformer', '/games/auto-platformer-v1/index.html', 2, 0, 0],
  ['Platformer 3', 'auto-platformer-v2', 'Play Platformer 3 - Platform adventure!', 'Platformer', '/games/auto-platformer-v2/index.html', 2, 0, 0],
  ['PoA Redis Fencing - Interactive Scenarios', 'fuellabs-fuel-core', 'Play PoA Redis Fencing - Interactive Scenarios - Puzzle game!', 'Puzzle', '/games/fuellabs-fuel-core/index.html', 1, 0, 0],
  ['Pong 1', 'auto-pong-v0', 'Play Pong 1 - Arcade game!', 'Arcade', '/games/auto-pong-v0/index.html', 2, 0, 0],
  ['Pong 2', 'auto-pong-v1', 'Play Pong 2 - Arcade game!', 'Arcade', '/games/auto-pong-v1/index.html', 2, 0, 0],
  ['Pong 3', 'auto-pong-v2', 'Play Pong 3 - Arcade game!', 'Arcade', '/games/auto-pong-v2/index.html', 2, 0, 0],
  ['Pong wars', 'vnglst-pong-wars', 'Play Pong wars - Puzzle game!', 'Puzzle', '/games/vnglst-pong-wars/index.html', 3, 0, 0],
  ['Pong!', 'jakesgordon-javascript-pong', 'Play Pong! - Arcade game!', 'Arcade', '/games/jakesgordon-javascript-pong/index.html', 5, 0, 0],
  ['Portals', 'markotaht-Portals', 'Play Portals - 3D game!', '3D', '/games/markotaht-Portals/index.html', 7, 0, 0],
  ['Portsmouth Snelly', 'portsmouth-snelly', 'Play Portsmouth Snelly - 3D game!', '3D', '/games/portsmouth-snelly/debugger.html', 10, 0, 0],
  ['Prelude of the Chambered - JavaScript', 'sbober-pocjs', 'Play Prelude of the Chambered - JavaScript - Arcade game!', 'Arcade', '/games/sbober-pocjs/index.html', 7, 0, 0],
  ['Premium Dominoes Master', 'Manthanvinzuda007-Academic-Projects-2024-2028', 'Play Premium Dominoes Master - Puzzle game!', 'Puzzle', '/games/Manthanvinzuda007-Academic-Projects-2024-2028/Dominoes Index.html', 57, 0, 0],
  ['proton.js / examples', 'drawcall-Proton', 'Play proton.js / examples - Puzzle game!', 'Puzzle', '/games/drawcall-Proton/index.html', 1, 0, 0],
  ['Radius Raid', 'jackrugile-radius-raid-js13k', 'Play Radius Raid - Puzzle game!', 'Puzzle', '/games/jackrugile-radius-raid-js13k/index.html', 4, 0, 0],
  ['Raycaster 1', 'auto-raycaster-v0', 'Play Raycaster 1 - Arcade game!', 'Arcade', '/games/auto-raycaster-v0/index.html', 2, 0, 0],
  ['Raycaster 2', 'auto-raycaster-v1', 'Play Raycaster 2 - Arcade game!', 'Arcade', '/games/auto-raycaster-v1/index.html', 2, 0, 0],
  ['Raycaster 3', 'auto-raycaster-v2', 'Play Raycaster 3 - Arcade game!', 'Arcade', '/games/auto-raycaster-v2/index.html', 2, 0, 0],
  ['React Three Fiber - First Person Movement', 'jgcarrillo-react-fp-movement', 'Play React Three Fiber - First Person Movement - 3D game!', '3D', '/games/jgcarrillo-react-fp-movement/index.html', 6, 0, 0],
  ['Reaction-Diffusion Playground - Introduction', 'jasonwebb-reaction-diffusion-playground', 'Play Reaction-Diffusion Playground - Introduction - Puzzle game!', 'Puzzle', '/games/jasonwebb-reaction-diffusion-playground/index.html', 8, 0, 0],
  ['ReceiptLine Designer', 'receiptline-receiptline', 'Play ReceiptLine Designer - Card game!', 'Card', '/games/receiptline-receiptline/index.html', 2, 0, 0],
  ['RecordRTC', 'muaz-khan-recordrtc', 'Play RecordRTC - Puzzle game!', 'Puzzle', '/games/muaz-khan-recordrtc/index.html', 1, 0, 0],
  ['Redblobgames Mapgen4', 'redblobgames-mapgen4', 'Play Redblobgames Mapgen4 - Puzzle game!', 'Puzzle', '/games/redblobgames-mapgen4/embed.html', 6, 0, 0],
  ['Redis Kaboom RPG Game', 'redis-developer-redis-kaboom-rpg', 'Play Redis Kaboom RPG Game - RPG adventure!', 'RPG', '/games/redis-developer-redis-kaboom-rpg/index.html', 1, 0, 0],
  ['ReKindle', 'rekindleos-rekindle', 'Play ReKindle - Puzzle game!', 'Puzzle', '/games/rekindleos-rekindle/index.html', 157, 0, 0],
  ['Repeater Panel', 'repplus-rep-chrome', 'Play Repeater Panel - Puzzle game!', 'Puzzle', '/games/repplus-rep-chrome/panel.html', 13, 0, 0],
  ['reveal.js – The HTML Presentation Framework', 'ditectrev-awesome-html-book-course-hypertext-markup-language', 'Play reveal.js – The HTML Presentation Framework - Puzzle game!', 'Puzzle', '/games/ditectrev-awesome-html-book-course-hypertext-markup-language/index.html', 1, 0, 0],
  ['Reversi 1', 'auto-reversi-v0', 'Play Reversi 1 - Arcade game!', 'Arcade', '/games/auto-reversi-v0/index.html', 2, 0, 0],
  ['Reversi 2', 'auto-reversi-v1', 'Play Reversi 2 - Arcade game!', 'Arcade', '/games/auto-reversi-v1/index.html', 2, 0, 0],
  ['Reversi 3', 'auto-reversi-v2', 'Play Reversi 3 - Arcade game!', 'Arcade', '/games/auto-reversi-v2/index.html', 2, 0, 0],
  ['RF Line of Sight - MeshForge', 'Nursedude-meshforge', 'Play RF Line of Sight - MeshForge - Puzzle game!', 'Puzzle', '/games/Nursedude-meshforge/los_visualization.html', 3, 0, 0],
  ['RF-DETR WebGPU - Analytics Dashboard', 'andyhuo520-rf-detr-detection', 'Play RF-DETR WebGPU - Analytics Dashboard - Card game!', 'Card', '/games/andyhuo520-rf-detr-detection/index.html', 11, 0, 0],
  ['Rhythm Tapper', 'auto-rhythm-tapper', 'Play Rhythm Tapper - Arcade game!', 'Arcade', '/games/auto-rhythm-tapper/index.html', 1, 0, 0],
  ['Ricbit Oldies', 'ricbit-Oldies', 'Play Ricbit Oldies - Puzzle game!', 'Puzzle', '/games/ricbit-Oldies/game.html', 3, 0, 0],
  ['Robin of Thirteensley', 'csubagio-js13k-robin', 'Play Robin of Thirteensley - Puzzle game!', 'Puzzle', '/games/csubagio-js13k-robin/index.html', 10, 0, 0],
  ['RPG Maker MV to ModernJS', 'bsides-rpgmakermv-modernjs', 'Play RPG Maker MV to ModernJS - RPG adventure!', 'RPG', '/games/bsides-rpgmakermv-modernjs/index.html', 5, 0, 0],
  ['Rpgtkoolmv Corescript', 'rpgtkoolmv-corescript', 'Play Rpgtkoolmv Corescript - RPG adventure!', 'RPG', '/games/rpgtkoolmv-corescript/index.html', 1, 0, 0],
  ['Rummy Cards', 'auto-rummy-cards', 'Play Rummy Cards - Racing challenge!', 'Card', '/games/auto-rummy-cards/index.html', 1, 0, 0],
  ['RustPixelGame', 'zipxing-rust_pixel', 'Play RustPixelGame - Arcade game!', 'Arcade', '/games/zipxing-rust_pixel/index.html', 2, 0, 0],
  ['Samyk Poisontap', 'samyk-poisontap', 'Play Samyk Poisontap - Puzzle game!', 'Puzzle', '/games/samyk-poisontap/target_injected_xhtmljs.html', 6, 0, 0],
  ['Sandbox Builder 1', 'auto-sandbox-v0', 'Play Sandbox Builder 1 - Puzzle game!', 'Puzzle', '/games/auto-sandbox-v0/index.html', 2, 0, 0],
  ['Sandbox Builder 2', 'auto-sandbox-v1', 'Play Sandbox Builder 2 - Puzzle game!', 'Puzzle', '/games/auto-sandbox-v1/index.html', 2, 0, 0],
  ['Sandbox Builder 3', 'auto-sandbox-v2', 'Play Sandbox Builder 3 - Puzzle game!', 'Puzzle', '/games/auto-sandbox-v2/index.html', 2, 0, 0],
  ['Sandbox Physics', 'auto-sandbox-physics', 'Play Sandbox Physics - Simulation game!', 'Simulation', '/games/auto-sandbox-physics/index.html', 1, 0, 0],
  ['sandspiel', 'maxbittker-sandspiel', 'Play sandspiel - Puzzle game!', 'Puzzle', '/games/maxbittker-sandspiel/index.html', 10, 0, 0],
  ['Sanrio', 'kvebox-sanrio', 'Play Sanrio - Arcade game!', 'Arcade', '/games/kvebox-sanrio/index.html', 5, 0, 0],
  ['SC2K', 'pdeva-OpenSC2K', 'Play SC2K - Puzzle game!', 'Puzzle', '/games/pdeva-OpenSC2K/index.html', 6, 0, 0],
  ['Schteppe Sweep And Prune', 'schteppe-sweep-and-prune', 'Play Schteppe Sweep And Prune - Arcade game!', 'Arcade', '/games/schteppe-sweep-and-prune/index.html', 3, 0, 0],
  ['Sector $$SECTOR_NAME - A randomly generated sector for Stars Without Number', 'nhr-swn', 'Play Sector $$SECTOR_NAME - A randomly generated sector for Stars Without Number - Puzzle game!', 'Puzzle', '/games/nhr-swn/swn.html', 12, 0, 0],
  ['Shaku - Demos', 'RonenNess-Shaku', 'Play Shaku - Demos - Arcade game!', 'Arcade', '/games/RonenNess-Shaku/index.html', 42, 0, 0],
  ['Shaunlebron Bl1nd Ld28', 'shaunlebron-bl1nd-ld28', 'Play Shaunlebron Bl1nd Ld28 - Puzzle game!', 'Puzzle', '/games/shaunlebron-bl1nd-ld28/index.html', 5, 0, 0],
  ['Shunting-Yard Demonstration', 'michaelg29-yt-challenges', 'Play Shunting-Yard Demonstration - Arcade game!', 'Arcade', '/games/michaelg29-yt-challenges/index.html', 3, 0, 0],
  ['Simon Says', 'auto-simon-says-mnttmlj1', 'Play Simon Says - Arcade game!', 'Arcade', '/games/auto-simon-says-mnttmlj1/index.html', 2, 0, 0],
  ['Simple Quiz', 'ashket980-front-end-projects', 'Play Simple Quiz - Card game!', 'Card', '/games/ashket980-front-end-projects/index.html', 1, 0, 0],
  ['Simple Quiz', 'behnamazimi-practical-front-end-projects', 'Play Simple Quiz - Card game!', 'Card', '/games/behnamazimi-practical-front-end-projects/index.html', 1, 0, 0],
  ['SineRider', 'hackclub-sinerider', 'Play SineRider - Puzzle game!', 'Puzzle', '/games/hackclub-sinerider/index.html', 15, 0, 0],
  ['sketch.js', 'soulwire-sketch.js', 'Play sketch.js - Simulation game!', 'Simulation', '/games/soulwire-sketch.js/index.html', 4, 0, 0],
  ['sketcher.js', 'xibyte-jsketcher', 'Play sketcher.js - Arcade game!', 'Arcade', '/games/xibyte-jsketcher/sketcher.html', 2, 0, 0],
  ['Skifree.js', 'basicallydan-skifree.js', 'Play Skifree.js - Arcade game!', 'Arcade', '/games/basicallydan-skifree.js/index.html', 17, 0, 0],
  ['SkillSync Landing Page Test', 'ruanyf-ai-test-case', 'Play SkillSync Landing Page Test - Puzzle game!', 'Puzzle', '/games/ruanyf-ai-test-case/index.html', 3, 0, 0],
  ['Skycons', 'darkskyapp-skycons', 'Play Skycons - Puzzle game!', 'Puzzle', '/games/darkskyapp-skycons/index.html', 4, 0, 0],
  ['SkyEmu', 'skylersaleh-SkyEmu', 'Play SkyEmu - Puzzle game!', 'Puzzle', '/games/skylersaleh-SkyEmu/shell.html', 1, 0, 0],
  ['Sliding Puzzle', 'auto-sliding-puzzle', 'Play Sliding Puzzle - Arcade game!', 'Arcade', '/games/auto-sliding-puzzle/index.html', 1, 0, 0],
  ['sm64js', 'sm64js-sm64js', 'Play sm64js - Puzzle game!', 'Puzzle', '/games/sm64js-sm64js/index.html', 9, 0, 0],
  ['Snake 1', 'auto-snake-v0', 'Play Snake 1 - Classic snake arcade game!', 'Puzzle', '/games/auto-snake-v0/index.html', 2, 0, 0],
  ['Snake 2', 'auto-snake-v1', 'Play Snake 2 - Classic snake arcade game!', 'Puzzle', '/games/auto-snake-v1/index.html', 2, 0, 0],
  ['Snake 3', 'auto-snake-v2', 'Play Snake 3 - Classic snake arcade game!', 'Puzzle', '/games/auto-snake-v2/index.html', 2, 0, 0],
  ['Solitaire 1', 'auto-solitaire-v0', 'Play Solitaire 1 - Card game!', 'Card', '/games/auto-solitaire-v0/index.html', 2, 0, 0],
  ['Solitaire 2', 'auto-solitaire-v1', 'Play Solitaire 2 - Card game!', 'Card', '/games/auto-solitaire-v1/index.html', 2, 0, 0],
  ['Solitaire 3', 'auto-solitaire-v2', 'Play Solitaire 3 - Card game!', 'Card', '/games/auto-solitaire-v2/index.html', 2, 0, 0],
  ['Solitaire Spider', 'auto-solitaire-spider', 'Play Solitaire Spider - Card game!', 'Card', '/games/auto-solitaire-spider/index.html', 1, 0, 0],
  ['Sonant-X Live', 'nicolas-van-sonant-x-live', 'Play Sonant-X Live - Arcade game!', 'Arcade', '/games/nicolas-van-sonant-x-live/index.html', 14, 0, 0],
  ['SoundManager 2: JavaScript Sound For The Web', 'scottschiller-soundmanager2', 'Play SoundManager 2: JavaScript Sound For The Web - Puzzle game!', 'Puzzle', '/games/scottschiller-soundmanager2/index.html', 1, 0, 0],
  ['Space Game v0.1', 'ygpydh-space-game', 'Play Space Game v0.1 - Shooting game!', 'Shooting', '/games/ygpydh-space-game/index.html', 5, 0, 0],
  ['Space Invaders 1', 'auto-space-invaders-v0', 'Play Space Invaders 1 - Space shooter arcade!', 'Shooting', '/games/auto-space-invaders-v0/index.html', 2, 0, 0],
  ['Space Invaders 2', 'auto-space-invaders-v1', 'Play Space Invaders 2 - Space shooter arcade!', 'Shooting', '/games/auto-space-invaders-v1/index.html', 2, 0, 0],
  ['Space Invaders 3', 'auto-space-invaders-v2', 'Play Space Invaders 3 - Space shooter arcade!', 'Shooting', '/games/auto-space-invaders-v2/index.html', 2, 0, 0],
  ['Space Invaders Deluxe', 'auto-space-invaders-deluxe', 'Play Space Invaders Deluxe - Space shooter arcade!', 'Shooting', '/games/auto-space-invaders-deluxe/index.html', 1, 0, 0],
  ['Splat', 'charliegerard-splat', 'Play Splat - 3D game!', '3D', '/games/charliegerard-splat/index.html', 4, 0, 0],
  ['SSD Advisory - NVMS9000 Information Disclosure - SSD Secure Disclosure', 'Mr-xn-Penetration_Testing_POC', 'Play SSD Advisory - NVMS9000 Information Disclosure - SSD Secure Disclosure - Puzzle game!', 'Puzzle', '/games/Mr-xn-Penetration_Testing_POC/SSD Advisory - NVMS9000 Information Disclosure - SSD Secure Disclosure.html', 30, 0, 0],
  ['Star Battle', 'gd4Ark-star-battle', 'Play Star Battle - Shooting game!', 'Shooting', '/games/gd4Ark-star-battle/index.html', 5, 0, 0],
  ['StarCraft', 'gloomyson-SC_Js', 'Play StarCraft - Puzzle game!', 'Puzzle', '/games/gloomyson-SC_Js/index.html', 4, 0, 0],
  ['steggibois', 'byu-csa-old-ctf-challenges', 'Play steggibois - 3D game!', '3D', '/games/byu-csa-old-ctf-challenges/index.html', 1, 0, 0],
  ['Sudoku 1', 'auto-sudoku-v0', 'Play Sudoku 1 - Number puzzle challenge!', 'Puzzle', '/games/auto-sudoku-v0/index.html', 2, 0, 0],
  ['Sudoku 2', 'auto-sudoku-v1', 'Play Sudoku 2 - Number puzzle challenge!', 'Puzzle', '/games/auto-sudoku-v1/index.html', 2, 0, 0],
  ['Sudoku 3', 'auto-sudoku-v2', 'Play Sudoku 3 - Number puzzle challenge!', 'Puzzle', '/games/auto-sudoku-v2/index.html', 2, 0, 0],
  ['Sudoku Solver', 'auto-sudoku-solver', 'Play Sudoku Solver - Number puzzle challenge!', 'Puzzle', '/games/auto-sudoku-solver/index.html', 1, 0, 0],
  ['Super Breakout', 'auto-super-breakout', 'Play Super Breakout - Break the bricks!', 'Puzzle', '/games/auto-super-breakout/index.html', 1, 0, 0],
  ['SUPER HOPPER', 'hamse122-SUPER-HOPPER', 'Play SUPER HOPPER - Platformer game!', 'Platformer', '/games/hamse122-SUPER-HOPPER/index.html', 5, 0, 0],
  ['Super Platformer', 'auto-super-platformer', 'Play Super Platformer - Platform adventure!', 'Platformer', '/games/auto-super-platformer/index.html', 1, 0, 0],
  ['SURVIVOR (1982 Commodore 64 game remake)', 'scottschiller-SURVIVOR', 'Play SURVIVOR (1982 Commodore 64 game remake) - Puzzle game!', 'Puzzle', '/games/scottschiller-SURVIVOR/index.html', 4, 0, 0],
  ['System Animator - Settings', 'butzyung-systemanimatoronline', 'Play System Animator - Settings - Puzzle game!', 'Puzzle', '/games/butzyung-systemanimatoronline/settings.html', 35, 0, 0],
  ['Talha - Crossy Road Game Clone', 'mdsahil011-crossy-road-game', 'Play Talha - Crossy Road Game Clone - Arcade game!', 'Arcade', '/games/mdsahil011-crossy-road-game/index.html', 1, 0, 0],
  ['Talha - Doodle Jump', 'he-is-talha-html-css-javascript-games', 'Play Talha - Doodle Jump - Platformer game!', 'Platformer', '/games/he-is-talha-html-css-javascript-games/index.html', 3, 0, 0],
  ['Talking Head', 'met4citizen-talkinghead', 'Play Talking Head - Puzzle game!', 'Puzzle', '/games/met4citizen-talkinghead/index.html', 7, 0, 0],
  ['Tank Battle', 'auto-tank-battle-mnttmliy', 'Play Tank Battle - Arcade game!', 'Arcade', '/games/auto-tank-battle-mnttmliy/index.html', 2, 0, 0],
  ['Tank Battle 1', 'auto-tank-v0', 'Play Tank Battle 1 - Arcade game!', 'Arcade', '/games/auto-tank-v0/index.html', 2, 0, 0],
  ['Tank Battle 2', 'auto-tank-v1', 'Play Tank Battle 2 - Arcade game!', 'Arcade', '/games/auto-tank-v1/index.html', 2, 0, 0],
  ['Tank Battle 3', 'auto-tank-v2', 'Play Tank Battle 3 - Arcade game!', 'Arcade', '/games/auto-tank-v2/index.html', 2, 0, 0],
  ['Tatris', 'jbreckmckye-nortis', 'Play Tatris - Arcade game!', 'Arcade', '/games/jbreckmckye-nortis/index.html', 2, 0, 0],
  ['terrain test', 'maptalks-maptalks.js', 'Play terrain test - Racing game!', 'Racing', '/games/maptalks-maptalks.js/terrain.html', 1, 0, 0],
  ['Tetr.js', 'simonlc-tetr.js', 'Play Tetr.js - Puzzle game!', 'Puzzle', '/games/simonlc-tetr.js/index.html', 1, 0, 0],
  ['Tetris 1', 'auto-tetris-v0', 'Play Tetris 1 - Block puzzle challenge!', 'Puzzle', '/games/auto-tetris-v0/index.html', 2, 0, 0],
  ['Tetris 2', 'auto-tetris-v1', 'Play Tetris 2 - Block puzzle challenge!', 'Puzzle', '/games/auto-tetris-v1/index.html', 2, 0, 0],
  ['Tetris 3', 'auto-tetris-v2', 'Play Tetris 3 - Block puzzle challenge!', 'Puzzle', '/games/auto-tetris-v2/index.html', 2, 0, 0],
  ['Tetris AI', 'LeeYiyuan-tetrisai', 'Play Tetris AI - Block puzzle challenge!', 'Puzzle', '/games/LeeYiyuan-tetrisai/index.html', 3, 0, 0],
  ['Tetris Battle', 'auto-tetris-battle', 'Play Tetris Battle - Block puzzle challenge!', 'Puzzle', '/games/auto-tetris-battle/index.html', 1, 0, 0],
  ['Tetris Game JS', 'CodeExplainedRepo-Tetris-JavaScript', 'Play Tetris Game JS - Block puzzle challenge!', 'Puzzle', '/games/CodeExplainedRepo-Tetris-JavaScript/index.html', 1, 0, 0],
  ['Tetris Game JS', 'tetris-ce', 'Play Tetris Game JS - Block puzzle challenge!', 'Puzzle', '/games/tetris-ce/index.html', 1, 0, 0],
  ['Tettet', 'abdyek-4ClassicGames', 'Play Tettet - Arcade game!', 'Arcade', '/games/abdyek-4ClassicGames/tettet.html', 3, 0, 0],
  ['The Big-Data Ecosystem Table', 'zenkay-bigdata-ecosystem', 'Play The Big-Data Ecosystem Table - Puzzle game!', 'Puzzle', '/games/zenkay-bigdata-ecosystem/bigdataecosystemtable.html', 9, 0, 0],
  ['The X Toolkit API', 'xtk-X', 'Play The X Toolkit API - Puzzle game!', 'Puzzle', '/games/xtk-X/camera.html', 69, 0, 0],
  ['ThreeCraft', 'gionathas-ThreeCraft', 'Play ThreeCraft - 3D game!', '3D', '/games/gionathas-ThreeCraft/index.html', 6, 0, 0],
  ['Tic Tac Toe 1', 'auto-tictactoe-v0', 'Play Tic Tac Toe 1 - Arcade game!', 'Arcade', '/games/auto-tictactoe-v0/index.html', 2, 0, 0],
  ['Tic Tac Toe 2', 'auto-tictactoe-v1', 'Play Tic Tac Toe 2 - Arcade game!', 'Arcade', '/games/auto-tictactoe-v1/index.html', 2, 0, 0],
  ['Tic Tac Toe 3', 'auto-tictactoe-v2', 'Play Tic Tac Toe 3 - Arcade game!', 'Arcade', '/games/auto-tictactoe-v2/index.html', 2, 0, 0],
  ['Time Smoothing', 'MysteryPancake-Houdini-Fun', 'Play Time Smoothing - Puzzle game!', 'Puzzle', '/games/MysteryPancake-Houdini-Fun/TimeSmoothing.html', 12, 0, 0],
  ['Tinspin Fuse', 'tinspin-fuse', 'Play Tinspin Fuse - Puzzle game!', 'Puzzle', '/games/tinspin-fuse/cube.html', 11, 0, 0],
  ['title', 'robin-dela-hover-effect', 'Play title - Puzzle game!', 'Puzzle', '/games/robin-dela-hover-effect/index.html', 5, 0, 0],
  ['Torinmb Mediapipe Touchdesigner', 'torinmb-mediapipe-touchdesigner', 'Play Torinmb Mediapipe Touchdesigner - Arcade game!', 'Arcade', '/games/torinmb-mediapipe-touchdesigner/index.html', 10, 0, 0],
  ['Tower Blocks 1', 'auto-tower-blocks-v0', 'Play Tower Blocks 1 - Puzzle game!', 'Puzzle', '/games/auto-tower-blocks-v0/index.html', 2, 0, 0],
  ['Tower Blocks 2', 'auto-tower-blocks-v1', 'Play Tower Blocks 2 - Puzzle game!', 'Puzzle', '/games/auto-tower-blocks-v1/index.html', 2, 0, 0],
  ['Tower Blocks 3', 'auto-tower-blocks-v2', 'Play Tower Blocks 3 - Puzzle game!', 'Puzzle', '/games/auto-tower-blocks-v2/index.html', 2, 0, 0],
  ['Tower Defense 1', 'auto-tower-defense-v0', 'Play Tower Defense 1 - Strategy defense!', 'Strategy', '/games/auto-tower-defense-v0/index.html', 2, 0, 0],
  ['Tower Defense 2', 'auto-tower-defense-v1', 'Play Tower Defense 2 - Strategy defense!', 'Strategy', '/games/auto-tower-defense-v1/index.html', 2, 0, 0],
  ['Tower Defense 3', 'auto-tower-defense-v2', 'Play Tower Defense 3 - Strategy defense!', 'Strategy', '/games/auto-tower-defense-v2/index.html', 2, 0, 0],
  ['Tower Defense Pro', 'auto-tower-defense-pro', 'Play Tower Defense Pro - Strategy defense!', 'Strategy', '/games/auto-tower-defense-pro/index.html', 1, 0, 0],
  ['Tower Platformer', 'jakesgordon-javascript-tower-platformer', 'Play Tower Platformer - Platform adventure!', 'Puzzle', '/games/jakesgordon-javascript-tower-platformer/index.html', 2, 0, 0],
  ['Treasure hunter', 'kittykatattack-hexi', 'Play Treasure hunter - Arcade game!', 'Arcade', '/games/kittykatattack-hexi/01_treasureHunter.html', 5, 0, 0],
  ['Treat Retriever', 'melluo-treat-retriever', 'Play Treat Retriever - Arcade game!', 'Arcade', '/games/melluo-treat-retriever/index.html', 7, 0, 0],
  ['Trishume Syntect', 'trishume-syntect', 'Play Trishume Syntect - 3D game!', '3D', '/games/trishume-syntect/test3.html', 8, 0, 0],
  ['TSG Suite', 'FiLORUX-tsg-vero-baambi', 'Play TSG Suite - Puzzle game!', 'Puzzle', '/games/FiLORUX-tsg-vero-baambi/index.html', 18, 0, 0],
  ['TTC', 'yelynn1-tictactoe', 'Play TTC - Puzzle game!', 'Puzzle', '/games/yelynn1-tictactoe/index.html', 1, 0, 0],
  ['Turret Defense', 'auto-turret-defense', 'Play Turret Defense - Shooting game!', 'Shooting', '/games/auto-turret-defense/index.html', 1, 0, 0],
  ['TWB Community Survey 2025', 'TheRosettaFoundation-SOLAS-Match', 'Play TWB Community Survey 2025 - Puzzle game!', 'Puzzle', '/games/TheRosettaFoundation-SOLAS-Match/user_TWB_Dashboard_Final.html', 8, 0, 0],
  ['Untrusted - a user javascript adventure game', 'alexnisnevich-untrusted', 'Play Untrusted - a user javascript adventure game - Puzzle game!', 'Puzzle', '/games/alexnisnevich-untrusted/index.html', 1, 0, 0],
  ['UT Package Summariser', 'bunnytrack-UTPackage.js', 'Play UT Package Summariser - Puzzle game!', 'Puzzle', '/games/bunnytrack-UTPackage.js/index.html', 2, 0, 0],
  ['Varunpant CrappyBird', 'varunpant-CrappyBird', 'Play Varunpant CrappyBird - Puzzle game!', 'Puzzle', '/games/varunpant-CrappyBird/index.html', 1, 0, 0],
  ['Vector Database Search', 'i3T4AN-Vector-Knowledge-Base', 'Play Vector Database Search - Puzzle game!', 'Puzzle', '/games/i3T4AN-Vector-Knowledge-Base/index.html', 11, 0, 0],
  ['Versor (libvsr)', 'wolftype-versor_1.0', 'Play Versor (libvsr) - Puzzle game!', 'Puzzle', '/games/wolftype-versor_1.0/index.html', 7, 0, 0],
  ['VideoDL 解析监控面板', 'CharlesPikachu-videodl', 'Play VideoDL 解析监控面板 - Puzzle game!', 'Puzzle', '/games/CharlesPikachu-videodl/index.html', 5, 0, 0],
  ['Vim.Wasm', 'rhysd-vim.wasm', 'Play Vim.Wasm - Arcade game!', 'Arcade', '/games/rhysd-vim.wasm/index.html', 13, 0, 0],
  ['Vite + TypeScript', 'jeantimex-splat', 'Play Vite + TypeScript - Arcade game!', 'Arcade', '/games/jeantimex-splat/index.html', 8, 0, 0],
  ['VOID STRIKE', 'TrebuchetNetwork-massive_game_server', 'Play VOID STRIKE - Shooting game!', 'Shooting', '/games/TrebuchetNetwork-massive_game_server/index.html', 27, 0, 0],
  ['VonWolfehaus Flow Field', 'vonWolfehaus-flow-field', 'Play VonWolfehaus Flow Field - Puzzle game!', 'Puzzle', '/games/vonWolfehaus-flow-field/index.html', 3, 0, 0],
  ['Voronota version 1.29', 'kliment-olechnovic-voronota', 'Play Voronota version 1.29 - Puzzle game!', 'Puzzle', '/games/kliment-olechnovic-voronota/index.html', 12, 0, 0],
  ['Voxel Runner 1', 'auto-voxel-v0', 'Play Voxel Runner 1 - Arcade game!', 'Arcade', '/games/auto-voxel-v0/index.html', 2, 0, 0],
  ['Voxel Runner 2', 'auto-voxel-v1', 'Play Voxel Runner 2 - Arcade game!', 'Arcade', '/games/auto-voxel-v1/index.html', 2, 0, 0],
  ['Voxel Runner 3', 'auto-voxel-v2', 'Play Voxel Runner 3 - Arcade game!', 'Arcade', '/games/auto-voxel-v2/index.html', 2, 0, 0],
  ['Voxel Terrain', 'auto-voxel-terrain', 'Play Voxel Terrain - 3D game!', '3D', '/games/auto-voxel-terrain/index.html', 1, 0, 0],
  ['VoxelCraft - Three.js Minecraft Clone', 'Angais-gpt5.3codex-3dblockgame', 'Play VoxelCraft - Three.js Minecraft Clone - Puzzle game!', 'Puzzle', '/games/Angais-gpt5.3codex-3dblockgame/index.html', 3, 0, 0],
  ['VRodos — Phase 0: pmndrs/postprocessing × Three r173 smoke test', 'VRodos-VRodos', 'Play VRodos — Phase 0: pmndrs/postprocessing × Three r173 smoke test - Puzzle game!', 'Puzzle', '/games/VRodos-VRodos/phase0-pmndrs-smoke-test.html', 16, 0, 0],
  ['Vue + Phaser 3', 'sun0fabeach-vue-phaser3', 'Play Vue + Phaser 3 - Arcade game!', 'Arcade', '/games/sun0fabeach-vue-phaser3/index.html', 2, 0, 0],
  ['Wave Shooter 1', 'auto-wave-shooter-v0', 'Play Wave Shooter 1 - Action shooter!', 'Shooting', '/games/auto-wave-shooter-v0/index.html', 2, 0, 0],
  ['Wave Shooter 2', 'auto-wave-shooter-v1', 'Play Wave Shooter 2 - Action shooter!', 'Shooting', '/games/auto-wave-shooter-v1/index.html', 2, 0, 0],
  ['Wave Shooter 3', 'auto-wave-shooter-v2', 'Play Wave Shooter 3 - Action shooter!', 'Shooting', '/games/auto-wave-shooter-v2/index.html', 2, 0, 0],
  ['Wave simulation', 'dionyziz-wave-experiment', 'Play Wave simulation - Simulation game!', 'Simulation', '/games/dionyziz-wave-experiment/index.html', 3, 0, 0],
  ['WebGPU e2eest', 'munrocket-double-js', 'Play WebGPU e2eest - Puzzle game!', 'Puzzle', '/games/munrocket-double-js/test.html', 1, 0, 0],
  ['WMTS服务及地图瓦片原理-CSDN博客', 'githubli1123-CesiumExampleCollection', 'Play WMTS服务及地图瓦片原理-CSDN博客 - Puzzle game!', 'Puzzle', '/games/githubli1123-CesiumExampleCollection/WMTS服务及地图瓦片原理.html', 2, 0, 0],
  ['wookmark.js', 'germanysbestkeptsecret-Wookmark-jQuery', 'Play wookmark.js - Puzzle game!', 'Puzzle', '/games/germanysbestkeptsecret-Wookmark-jQuery/wookmark.html', 3, 0, 0],
  ['word pluck - a browser based typing game', 'knadh-wordpluck', 'Play word pluck - a browser based typing game - Puzzle game!', 'Puzzle', '/games/knadh-wordpluck/index.html', 3, 0, 0],
  ['wordcloud2.js - tag cloud/Wordle presentation on 2D canvas or HTML', 'timdream-wordcloud2-js', 'Play wordcloud2.js - tag cloud/Wordle presentation on 2D canvas or HTML - Word puzzle!', 'Puzzle', '/games/timdream-wordcloud2-js/index.html', 1, 0, 0],
  ['Wordle 1', 'auto-wordle-v0', 'Play Wordle 1 - Word puzzle!', 'Puzzle', '/games/auto-wordle-v0/index.html', 2, 0, 0],
  ['Wordle 2', 'auto-wordle-v1', 'Play Wordle 2 - Word puzzle!', 'Puzzle', '/games/auto-wordle-v1/index.html', 2, 0, 0],
  ['Wordle 3', 'auto-wordle-v2', 'Play Wordle 3 - Word puzzle!', 'Puzzle', '/games/auto-wordle-v2/index.html', 2, 0, 0],
  ['Wordle Clone', 'auto-wordle-clone', 'Play Wordle Clone - Word puzzle!', 'Puzzle', '/games/auto-wordle-clone/index.html', 1, 0, 0],
  ['Wwasm', 'GMH-Code-Wwasm', 'Play Wwasm - Puzzle game!', 'Puzzle', '/games/GMH-Code-Wwasm/shell.html', 1, 0, 0],
  ['XMoto.js', 'MichaelHoste-xmoto.js', 'Play XMoto.js - Puzzle game!', 'Puzzle', '/games/MichaelHoste-xmoto.js/index.html', 11, 0, 0],
  ['XY Chart Test — Beautiful Mermaid', 'lukilabs-beautiful-mermaid', 'Play XY Chart Test — Beautiful Mermaid - Puzzle game!', 'Puzzle', '/games/lukilabs-beautiful-mermaid/xychart-test.html', 7, 0, 0],
  ['Zezombye Overpy', 'zezombye-overpy', 'Play Zezombye Overpy - Arcade game!', 'Arcade', '/games/zezombye-overpy/png_to_ascii.html', 11, 0, 0],
  ['Zombie Apocalypse', 'auto-zombie-apocalypse', 'Play Zombie Apocalypse - Shooting game!', 'Shooting', '/games/auto-zombie-apocalypse/index.html', 1, 0, 0],
  ['Zombie Shooter', 'auto-zombie-shooter-mnttmlj0', 'Play Zombie Shooter - Action shooter!', 'Shooting', '/games/auto-zombie-shooter-mnttmlj0/index.html', 2, 0, 0],
  ['Zombie Shooter 1', 'auto-zombie-v0', 'Play Zombie Shooter 1 - Action shooter!', 'Shooting', '/games/auto-zombie-v0/index.html', 2, 0, 0],
  ['Zombie Shooter 2', 'auto-zombie-v1', 'Play Zombie Shooter 2 - Action shooter!', 'Shooting', '/games/auto-zombie-v1/index.html', 2, 0, 0],
  ['Zombie Shooter 3', 'auto-zombie-v2', 'Play Zombie Shooter 3 - Action shooter!', 'Shooting', '/games/auto-zombie-v2/index.html', 2, 0, 0],
  ['Zuma', 'SkyisAakash-Zuma', 'Play Zuma - Shooting game!', 'Shooting', '/games/SkyisAakash-Zuma/index.html', 6, 0, 0],
  ['ZzFX - Zuper Zmall Zound Zynth', 'killedbyapixel-zzfx', 'Play ZzFX - Zuper Zmall Zound Zynth - Shooting game!', 'Shooting', '/games/killedbyapixel-zzfx/index.html', 1, 0, 0],
  ['苏州全民编程挑战赛', 'FreeCodeCampChina-freecodecamp.cn', 'Play 苏州全民编程挑战赛 - Puzzle game!', 'Puzzle', '/games/FreeCodeCampChina-freecodecamp.cn/code.html', 7, 0, 0],
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = games;
}

export { games };